"""Move a folder of renders into `screenshots/archive/`, dated.

Archiving is for renders that **cannot be produced again** -- typically because the tool that
made them was deleted in the commit that acted on what they showed. Everything else under
`screenshots/` is regenerable and should be regenerated rather than archived: `current/` and
`diff/` by `make shots`, `vas_layouts/` by `make layouts`.

    make archive ARGS="tick_variants"
    make archive ARGS="tick_variants --as tick-candidates"

The date comes from the newest file in the folder, not from today: the point of the name is
when the renders were made and the decision taken, which is not necessarily when someone got
round to filing them.

This exists because `mv` is denied to the agent (CLAUDE.md), and rightly -- it is a way to
destroy work without the permission rules seeing it. A named, bounded operation that only ever
moves a folder from `screenshots/` into `screenshots/archive/` is the safe version of it.
"""

from __future__ import annotations

import argparse
import datetime as dt
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tatp import config as cfg  # noqa: E402
from tatp.screenshots import SCREENSHOT_DIR  # noqa: E402

ARCHIVE_DIR = SCREENSHOT_DIR / "archive"
# Regenerable output. Archiving one would preserve a copy that the next `make` run contradicts.
REGENERABLE = ("current", "diff", "reference", "archive")


def newest_date(folder: Path) -> dt.date:
    files = [path for path in folder.rglob("*") if path.is_file()]
    if not files:
        raise SystemExit(f"{folder.relative_to(cfg.REPO_ROOT)} is empty; nothing to archive")
    newest = max(path.stat().st_mtime for path in files)
    return dt.datetime.fromtimestamp(newest).date()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("folder", help="a folder directly under screenshots/")
    parser.add_argument("--as", dest="name", default=None, help="archive under this name")
    args = parser.parse_args(argv)

    if "/" in args.folder or args.folder in ("", ".", ".."):
        raise SystemExit(f"{args.folder!r} is not a folder name directly under screenshots/")
    if args.folder in REGENERABLE:
        raise SystemExit(
            f"{args.folder} is regenerated by a make target, so archiving it would keep a copy "
            f"that the next run contradicts. Re-render it instead."
        )

    source = SCREENSHOT_DIR / args.folder
    if not source.is_dir():
        raise SystemExit(f"{source.relative_to(cfg.REPO_ROOT)} does not exist")

    destination = ARCHIVE_DIR / f"{args.name or args.folder}-{newest_date(source)}"
    if destination.exists():
        relative = destination.relative_to(cfg.REPO_ROOT)
        raise SystemExit(f"{relative} already exists; nothing moved")

    ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)
    shutil.move(str(source), str(destination))
    print(f"archived to {destination.relative_to(cfg.REPO_ROOT)}")
    print("Say what it records in screenshots/archive/README.md -- an unexplained folder of")
    print("old screens is indistinguishable from one nobody got round to deleting.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
