#!/usr/bin/env python3
"""Generate the counterbalancing file. SPEC.md 20 item 10.

Generated once and committed, so that every session of every participant reads the same
allocation. Regenerating it with the same seed reproduces it byte for byte; regenerating it
with a different seed after data collection has begun would silently re-allocate participants,
so the tool refuses to overwrite an existing file without --force.

    python tools/make_allocation.py
    python tools/make_allocation.py --seed 20260823 --out config/allocation.csv
"""

from __future__ import annotations

import argparse
import sys
from itertools import permutations
from pathlib import Path

import numpy as np
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

DEFAULT_SEED = 20260823


def build_rows(
    n_participants: int,
    n_sessions: int,
    conditions: list[str],
    limbs: list[str],
    seed: int,
):
    """One row per participant-session: (code, session, condition, limb).

    Condition order is a permutation of the conditions, drawn from a pool holding each
    permutation equally often, so the orders are balanced to within one participant however
    many participants there are.

    Target limb alternates between visits (SPEC.md 2). Which limb a participant starts on
    alternates by participant index, which balances the starting limb exactly rather than
    approximately -- with 41 participants a random assignment would not.
    """
    orders = sorted(permutations(conditions))
    if len(orders[0]) != n_sessions:
        raise ValueError(
            f"{n_sessions} sessions but {len(conditions)} conditions; a within-participant "
            f"counterbalance needs one session per condition"
        )
    rng = np.random.default_rng(seed)
    repeats = -(-n_participants // len(orders))  # ceiling division
    pool = [orders[i] for i in np.tile(np.arange(len(orders)), repeats)]
    rng.shuffle(pool)
    pool = pool[:n_participants]

    width = len(str(n_participants))
    rows = []
    for index, order in enumerate(pool):
        code = str(index + 1).zfill(width)
        start_limb = limbs[index % len(limbs)]
        for session in range(1, n_sessions + 1):
            limb = limbs[(limbs.index(start_limb) + session - 1) % len(limbs)]
            rows.append((code, session, order[session - 1], limb))
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--out", type=Path, default=REPO_ROOT / "config" / "allocation.csv")
    parser.add_argument("--force", action="store_true", help="overwrite an existing allocation")
    args = parser.parse_args()

    if args.out.exists() and not args.force:
        print(
            f"{args.out} already exists. Re-allocating participants after data collection has "
            f"begun would invalidate the counterbalance. Pass --force only if you are certain.",
            file=sys.stderr,
        )
        return 1

    study1 = yaml.safe_load((REPO_ROOT / "config" / "study1.yaml").read_text(encoding="utf-8"))
    design = study1["design"]
    rows = build_rows(
        design["n_participants"],
        design["n_sessions"],
        design["conditions"],
        design["limbs"],
        args.seed,
    )

    lines = [
        "# TATP Study 1 counterbalancing. Generated by tools/make_allocation.py -- do not "
        "edit.",
        f"# seed={args.seed} n_participants={design['n_participants']} "
        f"n_sessions={design['n_sessions']}",
        "participant_code,session_number,condition,limb",
    ]
    lines += [f"{code},{session},{condition},{limb}" for code, session, condition, limb in rows]
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {args.out} -- {len(rows)} rows, seed {args.seed}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
